"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from omegaconf import DictConfig

def compose(config_name: Optional[str] = ..., overrides: List[str] = ..., return_hydra_config: bool = ...) -> DictConfig:
    """
    :param config_name: the name of the config
           (usually the file name without the .yaml extension)
    :param overrides: list of overrides for config file
    :param return_hydra_config: True to return the hydra config node in the result
    :return: the composed config
    """
    ...

