"""
This type stub file was generated by pyright.
"""

import inspect
from dataclasses import dataclass
from typing import Any, Callable, Dict, List

@dataclass
class FunctionCall:
    name: str
    args: List[Any]
    kwargs: Dict[str, Any]
    ...


@dataclass
class Functions:
    definitions: Dict[str, inspect.Signature] = ...
    functions: Dict[str, Callable[..., Any]] = ...
    def register(self, name: str, func: Callable[..., Any]) -> None:
        ...
    
    def eval(self, func: FunctionCall) -> Any:
        ...
    


