"""
This type stub file was generated by pyright.
"""

from typing import Any

_ESC = ...
_ESC_REGEX = ...
def escape_special_characters(s: str) -> str:
    """Escape special characters in `s`"""
    ...

def is_type_matching(value: Any, type_: Any) -> bool:
    ...

