val_check_interval: 1.0
progress_bar_refresh_rate: 1

csv_log: True
wandb:
  project: georelations
  entity: null
  log_model: True
  mode: 'offline'

lr_monitor:
  logging_interval: "step"
  log_momentum: False
