"""
This type stub file was generated by pyright.
"""

from typing import Any
from hydra._internal.hydra import Hydra
from hydra.core.config_loader import ConfigLoader
from hydra.core.singleton import Singleton

class GlobalHydra(metaclass=Singleton):
    def __init__(self) -> None:
        ...
    
    def initialize(self, hydra: Hydra) -> None:
        ...
    
    def config_loader(self) -> ConfigLoader:
        ...
    
    def is_initialized(self) -> bool:
        ...
    
    def clear(self) -> None:
        ...
    
    @staticmethod
    def instance(*args: Any, **kwargs: Any) -> GlobalHydra:
        ...
    
    @staticmethod
    def set_instance(instance: GlobalHydra) -> None:
        ...
    


