"""
This type stub file was generated by pyright.
"""

from typing import Any
from omegaconf import DictConfig
from hydra.conf import HydraConf
from hydra.core.singleton import Singleton

class HydraConfig(metaclass=Singleton):
    def __init__(self) -> None:
        ...
    
    def set_config(self, cfg: DictConfig) -> None:
        ...
    
    @staticmethod
    def get() -> HydraConf:
        ...
    
    @staticmethod
    def initialized() -> bool:
        ...
    
    @staticmethod
    def instance(*args: Any, **kwargs: Any) -> HydraConfig:
        ...
    


