"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Type
from omegaconf import DictConfig
from hydra.core.config_loader import ConfigLoader
from hydra.core.singleton import Singleton
from hydra.plugins.launcher import Launcher
from hydra.plugins.plugin import Plugin
from hydra.plugins.sweeper import Sweeper
from hydra.types import TaskFunction

@dataclass
class ScanStats:
    total_time: float = ...
    total_modules_import_time: float = ...
    modules_import_time: Dict[str, float] = ...


class Plugins(metaclass=Singleton):
    @staticmethod
    def instance(*args: Any, **kwargs: Any) -> Plugins:
        ...
    
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def is_in_toplevel_plugins_module(clazz: str) -> bool:
        ...
    
    def instantiate_sweeper(self, config: DictConfig, config_loader: ConfigLoader, task_function: TaskFunction) -> Sweeper:
        ...
    
    def instantiate_launcher(self, config: DictConfig, config_loader: ConfigLoader, task_function: TaskFunction) -> Launcher:
        ...
    
    def get_stats(self) -> Optional[ScanStats]:
        ...
    
    def discover(self, plugin_type: Optional[Type[Plugin]] = ...) -> List[Type[Plugin]]:
        """
        :param plugin_type: class of plugin to discover, None for all
        :return: a list of plugins implementing the plugin type (or all if plugin type is None)
        """
        ...
    
    @staticmethod
    def check_usage(self_: Any) -> None:
        ...
    


