"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

class Singleton(type):
    _instances: Dict[type, Singleton] = ...
    def __call__(cls, *args: Any, **kwargs: Any) -> Any:
        ...
    
    def instance(cls: Any, *args: Any, **kwargs: Any) -> Any:
        ...
    
    @staticmethod
    def get_state() -> Any:
        ...
    
    @staticmethod
    def set_state(state: Any) -> None:
        ...
    


