"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Type
from hydra.core.singleton import Singleton
from hydra.plugins.config_source import ConfigSource

class SourcesRegistry(metaclass=Singleton):
    types: Dict[str, Type[ConfigSource]]
    def __init__(self) -> None:
        ...
    
    def register(self, type_: Type[ConfigSource]) -> None:
        ...
    
    def resolve(self, scheme: str) -> Type[ConfigSource]:
        ...
    
    @staticmethod
    def instance(*args: Any, **kwargs: Any) -> SourcesRegistry:
        ...
    


