"""
This type stub file was generated by pyright.
"""

import argparse
from typing import Any, List, Optional, Sequence, Tuple
from hydra.core.config_search_path import ConfigSearchPath

log = ...
def detect_calling_file_or_module_from_task_function(task_function: Any) -> Tuple[Optional[str], Optional[str], str]:
    ...

def detect_calling_file_or_module_from_stack_frame(stack_depth: int) -> Tuple[Optional[str], Optional[str]]:
    ...

def is_notebook() -> bool:
    ...

def detect_task_name(calling_file: Optional[str], calling_module: Optional[str]) -> str:
    ...

def compute_search_path_dir(calling_file: Optional[str], calling_module: Optional[str], config_path: Optional[str]) -> str:
    ...

def is_under_debugger() -> bool:
    """
    Attempts to detect if running under a debugger
    """
    ...

def create_automatic_config_search_path(calling_file: Optional[str], calling_module: Optional[str], config_path: Optional[str]) -> ConfigSearchPath:
    ...

def create_config_search_path(search_path_dir: Optional[str]) -> ConfigSearchPath:
    ...

def run_and_report(func: Any) -> Any:
    ...

def get_args_parser() -> argparse.ArgumentParser:
    class LazyCompletionHelp:
        ...
    
    

def get_args(args: Optional[Sequence[str]] = ...) -> Any:
    ...

def get_column_widths(matrix: List[List[str]]) -> List[int]:
    ...

