"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Optional
from .types import TaskFunction

def main(config_path: Optional[str] = ..., config_name: Optional[str] = ...) -> Callable[[TaskFunction], Any]:
    """
    :param config_path: the config path, a directory relative to the declaring python file.
    :param config_name: the name of the config (usually the file name without the .yaml extension)
    """
    ...

