"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable

log = ...
instantiate = ...
call = ...
ConvertMode = hydra.types.ConvertMode
def get_class(path: str) -> type:
    ...

def get_method(path: str) -> Callable[..., Any]:
    ...

get_static_method = ...
def get_original_cwd() -> str:
    """
    :return: the original working directory the Hydra application was launched from
    """
    ...

def to_absolute_path(path: str) -> str:
    """
    converts the specified path to be absolute path.
    if the input path is relative, it's interpreted as relative to the original working directory
    if it's absolute, it's returned as is
    :param path: path to convert
    :return:
    """
    ...

