optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-5
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.01

use_lr_scheduler: True
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: "max"
  verbose: True
  patience: 4

monitor_metric: "val_f1"
